// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: carauction/auction_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AuctionInfo struct {
	NextAssetId       uint64 `protobuf:"varint,1,opt,name=nextAssetId,proto3" json:"nextAssetId,omitempty"`
	NextLotId         uint64 `protobuf:"varint,2,opt,name=nextLotId,proto3" json:"nextLotId,omitempty"`
	FirstInQueueLotId uint64 `protobuf:"varint,3,opt,name=firstInQueueLotId,proto3" json:"firstInQueueLotId,omitempty"`
	LastInQueueLotId  uint64 `protobuf:"varint,4,opt,name=lastInQueueLotId,proto3" json:"lastInQueueLotId,omitempty"`
	FirstFinishTime   uint64 `protobuf:"varint,5,opt,name=firstFinishTime,proto3" json:"firstFinishTime,omitempty"`
}

func (m *AuctionInfo) Reset()         { *m = AuctionInfo{} }
func (m *AuctionInfo) String() string { return proto.CompactTextString(m) }
func (*AuctionInfo) ProtoMessage()    {}
func (*AuctionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba8cc925f7dc34fa, []int{0}
}
func (m *AuctionInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuctionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuctionInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuctionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuctionInfo.Merge(m, src)
}
func (m *AuctionInfo) XXX_Size() int {
	return m.Size()
}
func (m *AuctionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuctionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuctionInfo proto.InternalMessageInfo

func (m *AuctionInfo) GetNextAssetId() uint64 {
	if m != nil {
		return m.NextAssetId
	}
	return 0
}

func (m *AuctionInfo) GetNextLotId() uint64 {
	if m != nil {
		return m.NextLotId
	}
	return 0
}

func (m *AuctionInfo) GetFirstInQueueLotId() uint64 {
	if m != nil {
		return m.FirstInQueueLotId
	}
	return 0
}

func (m *AuctionInfo) GetLastInQueueLotId() uint64 {
	if m != nil {
		return m.LastInQueueLotId
	}
	return 0
}

func (m *AuctionInfo) GetFirstFinishTime() uint64 {
	if m != nil {
		return m.FirstFinishTime
	}
	return 0
}

func init() {
	proto.RegisterType((*AuctionInfo)(nil), "nasa70.carauction.carauction.AuctionInfo")
}

func init() { proto.RegisterFile("carauction/auction_info.proto", fileDescriptor_ba8cc925f7dc34fa) }

var fileDescriptor_ba8cc925f7dc34fa = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0x4e, 0x2c, 0x4a,
	0x2c, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x87, 0xd2, 0xf1, 0x99, 0x79, 0x69, 0xf9, 0x7a, 0x05,
	0x45, 0xf9, 0x25, 0xf9, 0x42, 0x32, 0x79, 0x89, 0xc5, 0x89, 0xe6, 0x06, 0x7a, 0x08, 0x55, 0x48,
	0x4c, 0xa5, 0x8b, 0x8c, 0x5c, 0xdc, 0x8e, 0x10, 0xb6, 0x67, 0x5e, 0x5a, 0xbe, 0x90, 0x02, 0x17,
	0x77, 0x5e, 0x6a, 0x45, 0x89, 0x63, 0x71, 0x71, 0x6a, 0x89, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x4b, 0x10, 0xb2, 0x90, 0x90, 0x0c, 0x17, 0x27, 0x88, 0xeb, 0x93, 0x0f, 0x92, 0x67, 0x02,
	0xcb, 0x23, 0x04, 0x84, 0x74, 0xb8, 0x04, 0xd3, 0x32, 0x8b, 0x8a, 0x4b, 0x3c, 0xf3, 0x02, 0x4b,
	0x53, 0x4b, 0x53, 0x21, 0xaa, 0x98, 0xc1, 0xaa, 0x30, 0x25, 0x84, 0xb4, 0xb8, 0x04, 0x72, 0x12,
	0xd1, 0x14, 0xb3, 0x80, 0x15, 0x63, 0x88, 0x0b, 0x69, 0x70, 0xf1, 0x83, 0x0d, 0x70, 0xcb, 0xcc,
	0xcb, 0x2c, 0xce, 0x08, 0xc9, 0xcc, 0x4d, 0x95, 0x60, 0x05, 0x2b, 0x45, 0x17, 0x76, 0xf2, 0x3a,
	0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63,
	0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0x83, 0xf4, 0xcc, 0x92, 0x8c, 0xd2,
	0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x48, 0xb0, 0xe8, 0x27, 0x27, 0x16, 0xe9, 0xc2, 0x42, 0xaf,
	0x42, 0x1f, 0x29, 0x28, 0x4b, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0x81, 0x68, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x29, 0xff, 0x42, 0xb2, 0x65, 0x01, 0x00, 0x00,
}

func (m *AuctionInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuctionInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuctionInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FirstFinishTime != 0 {
		i = encodeVarintAuctionInfo(dAtA, i, uint64(m.FirstFinishTime))
		i--
		dAtA[i] = 0x28
	}
	if m.LastInQueueLotId != 0 {
		i = encodeVarintAuctionInfo(dAtA, i, uint64(m.LastInQueueLotId))
		i--
		dAtA[i] = 0x20
	}
	if m.FirstInQueueLotId != 0 {
		i = encodeVarintAuctionInfo(dAtA, i, uint64(m.FirstInQueueLotId))
		i--
		dAtA[i] = 0x18
	}
	if m.NextLotId != 0 {
		i = encodeVarintAuctionInfo(dAtA, i, uint64(m.NextLotId))
		i--
		dAtA[i] = 0x10
	}
	if m.NextAssetId != 0 {
		i = encodeVarintAuctionInfo(dAtA, i, uint64(m.NextAssetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuctionInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuctionInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AuctionInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NextAssetId != 0 {
		n += 1 + sovAuctionInfo(uint64(m.NextAssetId))
	}
	if m.NextLotId != 0 {
		n += 1 + sovAuctionInfo(uint64(m.NextLotId))
	}
	if m.FirstInQueueLotId != 0 {
		n += 1 + sovAuctionInfo(uint64(m.FirstInQueueLotId))
	}
	if m.LastInQueueLotId != 0 {
		n += 1 + sovAuctionInfo(uint64(m.LastInQueueLotId))
	}
	if m.FirstFinishTime != 0 {
		n += 1 + sovAuctionInfo(uint64(m.FirstFinishTime))
	}
	return n
}

func sovAuctionInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuctionInfo(x uint64) (n int) {
	return sovAuctionInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AuctionInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuctionInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuctionInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuctionInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextAssetId", wireType)
			}
			m.NextAssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuctionInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextAssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextLotId", wireType)
			}
			m.NextLotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuctionInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextLotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstInQueueLotId", wireType)
			}
			m.FirstInQueueLotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuctionInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstInQueueLotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastInQueueLotId", wireType)
			}
			m.LastInQueueLotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuctionInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastInQueueLotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstFinishTime", wireType)
			}
			m.FirstFinishTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuctionInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstFinishTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAuctionInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuctionInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuctionInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuctionInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuctionInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuctionInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuctionInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuctionInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuctionInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuctionInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuctionInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuctionInfo = fmt.Errorf("proto: unexpected end of group")
)
